server:
  port: 8080
  servlet:
    context-path: /email-authenticator/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yarufchat
    username: jarufe
    password: GAJ@2003
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  redis:
#    host: 127.0.0.1
#    port: 6379
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: yarufzap@gmail.com
#    password: pcqp kztu nbnd iqhd
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace